# Site settings
title: "Patrik Štrba"
email: patrik.strba@gmail.com
description: "Patrik Strba - Software Developer - Personal Homepage"
baseurl: ""
url: "http://www.patrikstrba.com"
title_description: "Hi, my name is Patrik and im a Software Deveoper. Im working in Slovak startup Nicereply.com."
title_image: "https://s.gravatar.com/avatar/118eb4422906fd33f573a33443eec396?s=150"
google_analytics: "UA-6678902-1"
disqus_account: patrikstrba
github_repository: https://github.com/pajon/
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: _PatrikStrba
github_username:  pajon
linkedin_link: https://www.linkedin.com/in/patrikstrba
google_plus_link:
stackoverflow_link:

# Footer
footer_left: ""
footer_right: "" 

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
