# Site settings
title: "Patrik Štrba"
email: patrik.strba@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://www.patrikstrba.com/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://s.gravatar.com/avatar/118eb4422906fd33f573a33443eec396?s=150"
google_analytics: ""
disqus_account: 
github_repository: https://github.compajon/
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: _PatrikStrba
github_username:  pajon
linkedin_link: https://www.linkedin.com/in/patrikstrba
google_plus_link:
stackoverflow_link:

# Footer
footer_left: ""
footer_right: "" 

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
